title: Mould Press
author: Surbhi B
description: > # this means to ignore newlines until "baseurl:"
  Musings from a mouldy planet

# social links
twitter_username: _surbhib
show_excerpts: true # set to false to remove excerpts on the homepage

remote_theme: hpshinde/tufte-jekyll